<project>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.cavetale.pom</groupId>
    <artifactId>cavetale-pom-base</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <groupId>com.cavetale.watchman</groupId>
  <artifactId>watchman</artifactId>
  <version>0.1-SNAPSHOT</version>

  <name>Watchman</name>
  <url>https://github.com/StarTux/Watchman</url>
  <packaging>jar</packaging>

  <repositories>

    <!-- WorldEdit Repo -->
    <repository>
      <id>worldedit</id>
      <url>https://maven.enginehub.org/repo/</url>
    </repository>

  </repositories>
  <dependencies>

    <!-- Paper API -->
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- SQL -->
    <dependency>
      <groupId>com.winthier.sql</groupId>
      <artifactId>sql</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <!-- PlayerCache -->
    <dependency>
      <groupId>com.winthier.playercache</groupId>
      <artifactId>playercache</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <!-- Core -->
    <dependency>
      <groupId>com.cavetale.core</groupId>
      <artifactId>core</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <!-- WorldEdit -->
    <dependency>
      <groupId>com.sk89q.worldedit</groupId>
      <artifactId>worldedit-bukkit</artifactId>
      <version>7.3.0-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

    <!-- JUnit Testing -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>
</project>
