main: com.cavetale.watchman.WatchmanPlugin
name: Watchman

version: 0.1
api-version: 1.19

description: Player action logging tool
author: StarTux
website: http://cavetale.com

depend: [Core, SQL, PlayerCache]
softdepend: [WorldEdit]

commands:

  watchman:
    aliases: [ wm ]
    description: Watchman admin interface
    permission: watchman.watchman
    usage: |-
      Usage:
      /wm tool - Toggle block logging tool
      /wm clear - Clear your search
      /wm page <page> - View search page
      /wm info <id> - Detailed search result info
      /wm tp <id> - Teleport to log
      /wm open <id> - Open log inventory
      /wm lookup ARGS... - Search for records
        (a)ction:ACTION - Action type
        (p)layer:NAME - Player search
        (t)ime:XdXhXmXs - Limit time (d, h, m, s)
        (b)lock:block - The block type
        (i)tem:item - The item type
        (e)ntity:entity - The entity type
        (r)adius:RAD|world|global - Search radius
        (c)enter:X,Y - Center location
        (w)orld:WORLD - World name
      /wm rollback [id] - Rollback looked up records
      /wm rewind [seconds] [flags...] - Rewind WE selection
      /wm reload - Reload configuration

  wmtool:
    aliases: []
    permission: watchman.tool
    description: Toggle the Watchman tool
    usage: /wmtool - Toggle the Watchman tool

  wmpage:
    aliases: []
    permission: watchman.page
    description: Watchman paginator
    usage: /wmpage <index> - View pages

  rewind:
    aliases: []
    permission: watchman.rewind
    description: Block edit rewind
    usage: /rewind

permissions:

  watchman.watchman:
    description: Use /watchman
    default: op
  watchman.tool:
    description: Use /watchman tool
    default: op
  watchman.page:
    description: Use /wmpage
    default: op
  watchman.tool.detective:
    description: Show more actions with the tool
    default: op
  watchman.rollback:
    description: Use /watchman rollback
    default: op
  watchman.lookup:
    description: Use /watchman lookup
    default: op
  watchman.rewind:
    description: Use /watchman rewind
    default: op
  watchman.delete:
    description: Use /watchman delete
    default: op

  watchman.privacy.command:
    description: Commands are not recorded
    default: false

  watchman.privacy.chat:
    description: Chat is not recorded
    default: false