name: Watchman
description: Player action logging tool
author: StarTux
version: 0.1
api-version: 1.13
website: http://cavetale.com
main: com.cavetale.watchman.WatchmanPlugin
depend: [Dirty, SQL, PlayerCache, ProtocolLib]
softdepend: [WorldEdit]
commands:
  watchman:
    aliases: [ wm ]
    description: Watchman admin interface
    permission: watchman.watchman
    usage: |-
      Usage:
      /wm tool - Toggle block logging tool
      /wm rollback [id] - Rollback found records
      /wm clear - Clear your search
      /wm page PAGE - View search page
      /wm info ID - Detailed search result info
      /wm lookup ARGS... - Search for records
        (a)ction:ACTION - Action type
        (c)enter:X,Y - Center location
        (n)ew:TYPE - Placed block
        (o)ld:TYPE - Broken block or killed entity
        (p)layer:NAME - Player search
        (r)adius:RAD|world|global - Search radius
        (t)time:SECONDS - Limit time
        (w)orld:WORLD - World name
permissions:
  watchman.watchman:
    description: use /watchman
    default: op
  watchman.tool:
    description: use /watchman tool
    default: op
  watchman.rollback:
    description: use /watchman rollback
    default: op
  watchman.lookup:
    description: use /watchman lookup
    default: op
